name: Go

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  GO_VERSION: "1.20"

jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - name: Test
        run: go test ./... -v -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage profile
        uses: codecov/codecov-action@v3
